export const Colors = {
  primary: '#0056D2',
  primaryLight: '#E3F2FD',
  primaryLighter: '#F0F7FF',
  primaryDark: '#003D99',
  primaryForeground: '#FFFFFF',
  secondary: '#7C3AED',
  secondaryLight: '#F3E8FF',
  secondaryForeground: '#FFFFFF',
  background: '#F8FAFC',
  surface: '#FFFFFF',
  surfaceVariant: '#F1F5F9',
  textPrimary: '#1E293B',
  textSecondary: '#64748B',
  textMuted: '#94A3B8',
  border: '#E2E8F0',
  borderLight: '#F1F5F9',
  divider: '#CBD5E1',
  error: '#DC2626',
  errorLight: '#FEE2E2',
  errorLighter: '#FEF2F2',
  success: '#16A34A',
  successLight: '#DCFCE7',
  successLighter: '#F0FDF4',
  warning: '#D97706',
  warningLight: '#FEF3C7',
  warningLighter: '#FFFBEB',
  info: '#2563EB',
  infoLight: '#DBEAFE',
  infoLighter: '#F0F9FF',
  // Gradient colors
  gradientStart: '#0056D2',
  gradientMiddle: '#7C3AED',
  gradientEnd: '#EC4899',
  gradientAccent: '#F59E0B',
  // Card colors
  cardBackground: 'rgba(255, 255, 255, 0.98)',
  cardShadow: 'rgba(0, 0, 0, 0.08)',
  // Input colors
  inputBackground: '#F9FAFB',
  inputBorder: '#E5E7EB',
  inputFocus: '#0056D2',
  inputPlaceholder: '#9CA3AF',
  inputHover: '#F3F4F6',
};

export const StatusColors: Record<string, { bg: string; text: string; border?: string }> = {
  'Agendada': { bg: Colors.primaryLight, text: Colors.primary, border: Colors.primary },
  'Solicitud de modificación': { bg: Colors.warningLight, text: '#92400E', border: Colors.warning },
  'Solicitud de cancelación': { bg: Colors.errorLight, text: '#991B1B', border: Colors.error },
  'Asistió': { bg: Colors.successLight, text: '#065F46', border: Colors.success },
  'No asistió': { bg: Colors.errorLight, text: '#991B1B', border: Colors.error },
  'En ruta': { bg: Colors.infoLight, text: Colors.info, border: Colors.info },
  'Completada': { bg: Colors.successLight, text: Colors.success, border: Colors.success },
};
